name: Optiklink Build

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debugging information, disable optimization'
        required: true
        default: 'OFF'
        type: choice
        options:
        - 'ON'
        - 'OFF'
      unsafe:
        description: 'Enable unsafe features (fread, fwrite...)'
        required: true
        default: 'ON'
        type: choice
        options:
        - 'ON'
        - 'OFF'
      sqlite:
        description: 'SQLite support'
        required: true
        default: 'OFF'
        type: choice
        options:
        - 'ON'
        - 'OFF'
      curl:
        description: 'cURL support'
        required: true
        default: 'OFF'
        type: choice
        options:
        - 'ON'
        - 'OFF'
      ssl:
        description: 'SSL support (hash)'
        required: true
        default: 'OFF'
        type: choice
        options:
        - 'ON'
        - 'OFF'
      airjumps:
        description: 'Enable Air jumps'
        required: true
        default: 'OFF'
        type: choice
        options:
        - 'ON'
        - 'OFF'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: quay.io/mechamorph/iw1x-debian-buster

    env:
      BDEBUG: ${{ inputs.debug || 'OFF' }}
      BUNSAFE: ${{ inputs.unsafe || 'ON' }}
      BSQLITE: ${{ inputs.sqlite || 'OFF' }}
      BCURL: ${{ inputs.curl || 'OFF' }}
      BSSL: ${{ inputs.ssl || 'OFF' }}
      AIRJUMPS: ${{ inputs.airjumps || 'OFF' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      #- name: Install Dependencies
      #  run: |
      #    # Add i386 architecture so that 32-bit packages can be installed
      #    #dpkg --add-architecture i386
      #    #apt-get update

      #    # Required for building
      #    #apt-get install -y g++-multilib cmake libsqlite3-dev:i386 libcurl4-openssl-dev:i386 libssl-dev:i386

      - name: Configure Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DDEBUG_BUILD=$BDEBUG -DENABLE_UNSAFE=$BUNSAFE -DCOMPILE_SQLITE=$BSQLITE -DCOMPILE_CURL=$BCURL -DCOMPILE_SSL=$BSSL -DAIRJUMPS=$AIRJUMPS

      - name: Build
        run: |
          cd build
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iw1x library for Optiklink servers
          path: bin/libcod1.so
